use std::{
    collections::BTreeMap,
    env, fs,
    io::Write,
    path::{Path, PathBuf},
};

#[derive(Clone, Debug)]
struct ShortcutEntry {
    command_id: String,
    title: String,
    category: String,
    scope: String,
    shortcut: String,
}

fn main() {
    generate_shortcut_catalog();
    tauri_build::build()
}

fn generate_shortcut_catalog() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("missing CARGO_MANIFEST_DIR"));
    let menus_dir = manifest_dir.join("src/menus");
    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_else(|_| String::from("macos"));
    let is_macos = target_os == "macos";

    let mut entries = Vec::new();

    let menu_files = fs::read_dir(&menus_dir)
        .expect("failed to read src/menus directory")
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path())
        .filter(|path| path.extension().and_then(|ext| ext.to_str()) == Some("rs"))
        .filter(|path| path.file_name().and_then(|name| name.to_str()) != Some("mod.rs"))
        .collect::<Vec<_>>();

    for path in menu_files {
        println!("cargo:rerun-if-changed={}", path.display());
        let category = category_from_file(&path);
        let contents = fs::read_to_string(&path)
            .unwrap_or_else(|error| panic!("failed to read {}: {error}", path.display()));

        entries.extend(parse_shortcut_entries(&contents, &category, is_macos));
    }

    let mut unique = BTreeMap::<String, ShortcutEntry>::new();
    for entry in entries {
        unique.entry(entry.command_id.clone()).or_insert(entry);
    }

    let mut entries = unique.into_values().collect::<Vec<_>>();
    entries.sort_by(|left, right| {
        left.category
            .cmp(&right.category)
            .then(left.title.cmp(&right.title))
            .then(left.shortcut.cmp(&right.shortcut))
    });

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("missing OUT_DIR"));
    let out_path = out_dir.join("menu_shortcuts.rs");
    let mut file = fs::File::create(&out_path)
        .unwrap_or_else(|error| panic!("failed to create {}: {error}", out_path.display()));

    writeln!(
        file,
        "// @generated by build.rs; do not edit manually.\npub const MENU_SHORTCUT_SPECS: &[(&str, &str, &str, &str, Option<&str>)] = &["
    )
    .expect("failed to write generated shortcut catalog header");

    for entry in entries {
        writeln!(
            file,
            "    ({:?}, {:?}, {:?}, {:?}, Some({:?})),",
            entry.command_id, entry.title, entry.category, entry.scope, entry.shortcut
        )
        .expect("failed to write generated shortcut entry");
    }

    writeln!(file, "];").expect("failed to finish generated shortcut catalog");
}

fn parse_shortcut_entries(contents: &str, category: &str, is_macos: bool) -> Vec<ShortcutEntry> {
    let mut entries = Vec::new();

    for line in contents.lines() {
        let trimmed = line.trim();
        if let Some(entry) = parse_normal_menu_item(trimmed, category) {
            entries.push(entry);
            continue;
        }

        if let Some(entry) = parse_check_menu_item(trimmed, category) {
            entries.push(entry);
            continue;
        }

        if let Some(entry) = parse_predefined_menu_item(trimmed, category, is_macos) {
            entries.push(entry);
        }
    }

    entries
}

fn parse_normal_menu_item(line: &str, category: &str) -> Option<ShortcutEntry> {
    if !line.contains("MenuItem::with_id(") || !line.contains("Some(\"") {
        return None;
    }

    let quoted = quoted_strings(line);
    if quoted.len() < 3 {
        return None;
    }

    Some(ShortcutEntry {
        command_id: quoted[0].to_string(),
        title: quoted[1].to_string(),
        category: category.to_string(),
        scope: "menu".to_string(),
        shortcut: quoted[2].to_string(),
    })
}

fn parse_check_menu_item(line: &str, category: &str) -> Option<ShortcutEntry> {
    if !line.contains("CheckMenuItem::with_id(") || !line.contains("Some(\"") {
        return None;
    }

    let quoted = quoted_strings(line);
    if quoted.len() < 3 {
        return None;
    }

    Some(ShortcutEntry {
        command_id: quoted[0].to_string(),
        title: quoted[1].to_string(),
        category: category.to_string(),
        scope: "menu".to_string(),
        shortcut: quoted[2].to_string(),
    })
}

fn parse_predefined_menu_item(line: &str, category: &str, is_macos: bool) -> Option<ShortcutEntry> {
    let shortcut = match predefined_shortcut(line, is_macos) {
        Some(shortcut) => shortcut,
        None => return None,
    };

    let action = if line.contains("PredefinedMenuItem::copy(") {
        Some(("copy", "Copy"))
    } else if line.contains("PredefinedMenuItem::cut(") {
        Some(("cut", "Cut"))
    } else if line.contains("PredefinedMenuItem::paste(") {
        Some(("paste", "Paste"))
    } else if line.contains("PredefinedMenuItem::select_all(") {
        Some(("select-all", "Select All"))
    } else if line.contains("PredefinedMenuItem::undo(") {
        Some(("undo", "Undo"))
    } else if line.contains("PredefinedMenuItem::redo(") {
        Some(("redo", "Redo"))
    } else if line.contains("PredefinedMenuItem::hide_others(") {
        Some(("hide-others", "Hide Others"))
    } else if line.contains("PredefinedMenuItem::hide(") {
        Some(("hide", "Hide"))
    } else if line.contains("PredefinedMenuItem::close_window(") {
        Some(("close-window", "Close Window"))
    } else if line.contains("PredefinedMenuItem::quit(") {
        Some(("quit", "Quit"))
    } else {
        None
    }?;

    Some(ShortcutEntry {
        command_id: format!("predefined.{}.{}", category.to_lowercase(), action.0),
        title: action.1.to_string(),
        category: category.to_string(),
        scope: "menu".to_string(),
        shortcut,
    })
}

fn predefined_shortcut(line: &str, is_macos: bool) -> Option<String> {
    let primary = if is_macos { "Cmd" } else { "Ctrl" };

    if line.contains("PredefinedMenuItem::copy(") {
        Some(format!("{primary}+C"))
    } else if line.contains("PredefinedMenuItem::cut(") {
        Some(format!("{primary}+X"))
    } else if line.contains("PredefinedMenuItem::paste(") {
        Some(format!("{primary}+V"))
    } else if line.contains("PredefinedMenuItem::select_all(") {
        Some(format!("{primary}+A"))
    } else if line.contains("PredefinedMenuItem::undo(") {
        Some(format!("{primary}+Z"))
    } else if line.contains("PredefinedMenuItem::redo(") {
        if is_macos {
            Some(String::from("Shift+Cmd+Z"))
        } else {
            Some(format!("{primary}+Y"))
        }
    } else if line.contains("PredefinedMenuItem::hide_others(") {
        Some(format!("{primary}+Alt+H"))
    } else if line.contains("PredefinedMenuItem::hide(") {
        Some(format!("{primary}+H"))
    } else if line.contains("PredefinedMenuItem::close_window(") {
        if is_macos {
            Some(String::from("Cmd+W"))
        } else {
            Some(String::from("Alt+F4"))
        }
    } else if line.contains("PredefinedMenuItem::quit(") {
        if is_macos {
            Some(String::from("Cmd+Q"))
        } else {
            None
        }
    } else {
        None
    }
}

fn quoted_strings(line: &str) -> Vec<&str> {
    line.split('"')
        .enumerate()
        .filter_map(
            |(index, value)| {
                if index % 2 == 1 {
                    Some(value)
                } else {
                    None
                }
            },
        )
        .collect()
}

fn category_from_file(path: &Path) -> String {
    match path
        .file_stem()
        .and_then(|stem| stem.to_str())
        .unwrap_or_default()
    {
        "app" => String::from("App"),
        "file" => String::from("File"),
        "edit" => String::from("Edit"),
        "view" => String::from("View"),
        "tab" => String::from("Tab"),
        "blocks" => String::from("Blocks"),
        "ai" => String::from("AI"),
        other => {
            let mut chars = other.chars();
            match chars.next() {
                Some(first) => format!("{}{}", first.to_ascii_uppercase(), chars.as_str()),
                None => String::from("Menu"),
            }
        }
    }
}
