import { useMemoryStore } from '../../../../stores/memoryStore';
import type { TerminalCommandBlock } from '../../../../types/terminal';
import {
  collectTabConfigTemplateVariables,
  parseTabConfigToml
} from '../../utils/tabConfigs';
import type { TerminalSessionState } from '../../utils';

export const OPEN_CLOUD_PROFILE_DRAWER_EVENT = 'octomus:open-cloud-profile-drawer';
export const SETTINGS_TAB_ID = 'settings';

export type OpenCloudProfileDrawerPayload = {
  profileId: string;
  sectionId: string;
};

export function buildEmptyWorkspaceSnapshot(options: {
  activeSectionId: string;
  expandedGroupIds: string[];
  isAgentsActive: boolean;
  isSidebarOpen: boolean;
}) {
  return {
    id: 'workspace-main',
    schemaVersion: 1,
    tabs: [],
    selectedTabId: null,
    launcherTabId: null,
    paneLayoutsByTabId: {},
    conversations: [],
    terminalSessions: {},
    activeSectionId: options.activeSectionId,
    expandedGroupIds: options.expandedGroupIds,
    isSidebarOpen: options.isSidebarOpen,
    isAgentsActive: options.isAgentsActive,
    nextTerminalIndex: 1,
    nextConversationIndex: 1,
    updatedAt: new Date().toISOString()
  };
}

export function appearanceFlag(settings: ReturnType<typeof useMemoryStore.getState>['settings'], key: string) {
  const appearance = settings?.values.appearance;
  return Boolean(appearance && typeof appearance === 'object' && !Array.isArray(appearance) && (appearance as Record<string, unknown>)[key] === true);
}

export function latestUserPromptTitle(record: { messages?: Array<{ role?: string; body?: string }> } | null) {
  const latestUserMessage = record?.messages
    ?.slice()
    .reverse()
    .find((message) => message.role === 'user' && typeof message.body === 'string' && message.body.trim().length > 0);
  const title = latestUserMessage?.body?.trim() ?? null;

  if (!title) {
    return null;
  }

  return title.length > 80 ? `${title.slice(0, 79)}...` : title;
}

export function buildTabConfigTabId(fileName: string) {
  const base = fileName.replace(/\.toml$/i, '').replace(/[^a-zA-Z0-9_-]+/g, '-').replace(/-+/g, '-').replace(/^-+|-+$/g, '') || 'tab-config';
  return `tab-config-${base}-${Date.now()}`;
}

export function fileNameFromPath(path: string) {
  return path.split(/[\\/]/).pop() ?? path;
}

function sortCommandBlocksByExecutionTime(blocks: TerminalCommandBlock[]) {
  return [...blocks].sort((left, right) => {
    const leftTime = Date.parse(left.finishedAt || left.startedAt || '') || 0;
    const rightTime = Date.parse(right.finishedAt || right.startedAt || '') || 0;
    if (leftTime !== rightTime) {
      return leftTime - rightTime;
    }

    return left.id.localeCompare(right.id);
  });
}

export function latestFinishedCommandStatus(session: TerminalSessionState | undefined, fallbackStatus: string | null) {
  const finishedBlocks = sortCommandBlocksByExecutionTime([
    ...(session?.terminalBlocks ?? []),
    ...(session?.agentTerminalBlocks ?? [])
  ])
    .filter((block) => block.presentation !== 'conversation-link' && block.status === 'finished');
  const latestFinishedBlock = finishedBlocks[finishedBlocks.length - 1];

  if (latestFinishedBlock) {
    return typeof latestFinishedBlock.exitCode === 'number' && latestFinishedBlock.exitCode !== 0
      ? 'failed'
      : 'completed';
  }

  if (fallbackStatus === 'cancelled') {
    return 'cancelled';
  }

  if (fallbackStatus === 'failed') {
    return 'failed';
  }

  if (fallbackStatus === 'completed') {
    return 'completed';
  }

  return null;
}

export function promptForTabConfigVariables(config: ReturnType<typeof parseTabConfigToml>) {
  const variables = new Set(collectTabConfigTemplateVariables(config));
  const resolved: Record<string, string> = {};

  variables.forEach((variable) => {
    const defaultValue = config.params[variable]?.default?.trim() || '';
    if (variable === 'autogenerated_branch_name') {
      resolved[variable] = defaultValue || `branch-${Date.now()}`;
      return;
    }

    const description = config.params[variable]?.description?.trim();
    const promptLabel = description
      ? `${variable}\n${description}`
      : variable;
    const nextValue = window.prompt(`Tab config parameter: ${promptLabel}`, defaultValue);
    if (nextValue === null) {
      throw new Error('Tab config launch cancelled.');
    }

    resolved[variable] = nextValue;
  });

  return resolved;
}
